[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CGKruthin", email = "kruthin9900@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.4",
    "uvicorn>=0.52.1",
]



[dependency-groups]
dev = [
    "black>=26.5.1",
    "ruff>=0.16.1",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.black]
line-length = 88
target-version = ["py312"]
