import hashlib
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional
from uuid import UUID

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from shared.contracts.artifact import Artifact, ArtifactType
from shared.contracts.pdf import (
    CodeBlockElement,
    HeadingElement,
    ListElement,
    ParagraphElement,
    PDFDocumentInput,
    PDFElementType,
    PDFGenerationResult,
    TableElement,
)
from shared.contracts.permission import PermissionType

from app.core.exceptions import (
    InputValidationException,
    ToolExecutionException,
)
from app.core.logging import get_logger
from app.core.permissions import PermissionManager

logger = get_logger(__name__)


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and draw total page numbers and footers.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: List[Dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count: int) -> None:
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#718096"))

        # Footer divider line
        self.setLineWidth(0.5)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.line(54, 36, letter[0] - 54, 36)

        # Footer text
        footer_text = "Generated by AetherPhoenix Worker Agent"
        page_text = f"Page {self._pageNumber} of {page_count}"

        self.drawString(54, 22, footer_text)
        self.drawRightString(letter[0] - 54, 22, page_text)
        self.restoreState()


class PDFGenerator:
    """
    PDF Generator core module for converting structured content into PDF documents.
    """

    def __init__(
        self,
        permission_manager: Optional[PermissionManager] = None,
        allowed_base_dirs: Optional[List[Path]] = None,
    ) -> None:
        self.permission_manager = permission_manager
        self.allowed_base_dirs = allowed_base_dirs or []

    def validate_output_path(self, output_path: str) -> Path:
        """
        Validates and sanitizes the output file path to prevent directory traversal
        and ensure destination directory exists.

        Args:
            output_path: Path string for target PDF file.

        Returns:
            Resolved absolute Path object.

        Raises:
            InputValidationException: If path is invalid or outside allowed bounds.
        """
        if not output_path or not output_path.strip():
            raise InputValidationException(
                message="Output path cannot be empty.",
                details={"output_path": output_path},
            )

        # Disallow null bytes or illegal characters
        if "\0" in output_path:
            raise InputValidationException(
                message="Invalid output path containing null byte.",
                details={"output_path": output_path},
            )

        try:
            path_obj = Path(output_path).expanduser().resolve()
        except Exception as exc:
            raise InputValidationException(
                message=f"Failed to resolve target output path: {str(exc)}",
                details={"output_path": output_path, "error": str(exc)},
            ) from exc

        # Must end with .pdf extension
        if path_obj.suffix.lower() != ".pdf":
            raise InputValidationException(
                message="Output path must have a '.pdf' extension.",
                details={"output_path": str(path_obj)},
            )

        # Restrict destination path if allowed_base_dirs are specified
        if self.allowed_base_dirs:
            resolved_bases = [b.resolve() for b in self.allowed_base_dirs]
            is_allowed = any(
                path_obj == base or base in path_obj.parents for base in resolved_bases
            )
            if not is_allowed:
                raise InputValidationException(
                    message=(
                        f"Target path '{path_obj}' is outside approved directories."
                    ),
                    details={"output_path": str(path_obj)},
                )

        # Create parent directories safely
        try:
            path_obj.parent.mkdir(parents=True, exist_ok=True)
        except Exception as exc:
            raise InputValidationException(
                message=f"Cannot create directory for path '{path_obj}': {str(exc)}",
                details={"output_path": str(path_obj)},
            ) from exc

        return path_obj

    def check_permissions(self, workflow_id: Optional[UUID]) -> None:
        """
        Enforces FILE_SYSTEM permission check via PermissionManager if available.
        """
        if self.permission_manager and workflow_id:
            logger.info(
                f"Enforcing FILE_SYSTEM permission check for workflow {workflow_id}"
            )
            self.permission_manager.enforce_permission(
                PermissionType.FILE_SYSTEM, workflow_id
            )

    def generate(self, input_data: PDFDocumentInput) -> PDFGenerationResult:
        """
        Generates a PDF document from structured input data.

        Args:
            input_data: Validated PDFDocumentInput structure.

        Returns:
            PDFGenerationResult metadata object.

        Raises:
            InputValidationException: If input content is invalid.
            PermissionDeniedException: If FILE_SYSTEM permission is denied.
            ToolExecutionException: If PDF rendering fails.
        """
        start_time = time.time()

        # Step 1: Check Permissions
        self.check_permissions(input_data.workflow_id)

        # Step 2: Validate Path
        target_path = self.validate_output_path(input_data.output_path)

        # Step 3: Validate Content Input
        if not input_data.title and not input_data.elements:
            raise InputValidationException(
                message=(
                    "Document input must contain at least a title or content elements."
                ),
                details={
                    "title": input_data.title,
                    "element_count": len(input_data.elements),
                },
            )

        logger.info(
            f"Generating PDF '{input_data.title}' at '{target_path}' "
            f"with {len(input_data.elements)} content elements."
        )

        # Step 4: Build ReportLab Document Layout
        try:
            styles = getSampleStyleSheet()

            # Custom styles palette
            title_style = ParagraphStyle(
                "DocTitle",
                parent=styles["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=24,
                leading=28,
                textColor=colors.HexColor("#1A2530"),
                spaceAfter=6,
            )

            subtitle_style = ParagraphStyle(
                "DocSubtitle",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=13,
                leading=16,
                textColor=colors.HexColor("#4A5568"),
                spaceAfter=12,
            )

            meta_style = ParagraphStyle(
                "DocMeta",
                parent=styles["Normal"],
                fontName="Helvetica-Oblique",
                fontSize=9,
                leading=12,
                textColor=colors.HexColor("#718096"),
                spaceAfter=14,
            )

            h1_style = ParagraphStyle(
                "DocH1",
                parent=styles["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=16,
                leading=20,
                textColor=colors.HexColor("#2B6CB0"),
                spaceBefore=14,
                spaceAfter=8,
                keepWithNext=True,
            )

            h2_style = ParagraphStyle(
                "DocH2",
                parent=styles["Heading2"],
                fontName="Helvetica-Bold",
                fontSize=13,
                leading=16,
                textColor=colors.HexColor("#2D3748"),
                spaceBefore=10,
                spaceAfter=6,
                keepWithNext=True,
            )

            h3_style = ParagraphStyle(
                "DocH3",
                parent=styles["Heading3"],
                fontName="Helvetica-Bold",
                fontSize=11,
                leading=14,
                textColor=colors.HexColor("#4A5568"),
                spaceBefore=8,
                spaceAfter=4,
                keepWithNext=True,
            )

            body_style = ParagraphStyle(
                "DocBody",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=10,
                leading=14,
                textColor=colors.HexColor("#2D3748"),
                spaceAfter=6,
            )

            code_style = ParagraphStyle(
                "DocCode",
                parent=styles["Normal"],
                fontName="Courier",
                fontSize=8.5,
                leading=11,
                textColor=colors.HexColor("#1A202C"),
                backColor=colors.HexColor("#F7FAFC"),
                borderColor=colors.HexColor("#E2E8F0"),
                borderWidth=0.5,
                borderPadding=6,
                spaceBefore=6,
                spaceAfter=6,
            )

            flowables: List[Any] = []

            # Document Title
            if input_data.title:
                flowables.append(Paragraph(input_data.title, title_style))

            # Subtitle
            if input_data.subtitle:
                flowables.append(Paragraph(input_data.subtitle, subtitle_style))

            # Metadata (Author & Created Date)
            meta_parts = []
            if input_data.author:
                meta_parts.append(f"Author: {input_data.author}")
            meta_parts.append(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
            flowables.append(Paragraph(" | ".join(meta_parts), meta_style))

            # Divider line
            flowables.append(
                HRFlowable(
                    width="100%",
                    thickness=1,
                    color=colors.HexColor("#CBD5E0"),
                    spaceBefore=0,
                    spaceAfter=14,
                )
            )

            # Process Structured Content Elements
            for element in input_data.elements:
                if isinstance(element, HeadingElement) or (
                    isinstance(element, dict)
                    and element.get("element_type") == PDFElementType.HEADING
                ):
                    text = (
                        element.text
                        if isinstance(element, HeadingElement)
                        else element.get("text", "")
                    )
                    level = (
                        element.level
                        if isinstance(element, HeadingElement)
                        else element.get("level", 1)
                    )
                    style = (
                        h1_style
                        if level == 1
                        else (h2_style if level == 2 else h3_style)
                    )
                    flowables.append(Paragraph(text, style))

                elif isinstance(element, ParagraphElement) or (
                    isinstance(element, dict)
                    and element.get("element_type") == PDFElementType.PARAGRAPH
                ):
                    text = (
                        element.text
                        if isinstance(element, ParagraphElement)
                        else element.get("text", "")
                    )
                    bold = (
                        element.bold
                        if isinstance(element, ParagraphElement)
                        else element.get("bold", False)
                    )
                    italic = (
                        element.italic
                        if isinstance(element, ParagraphElement)
                        else element.get("italic", False)
                    )

                    formatted_text = text
                    if bold:
                        formatted_text = f"<b>{formatted_text}</b>"
                    if italic:
                        formatted_text = f"<i>{formatted_text}</i>"

                    flowables.append(Paragraph(formatted_text, body_style))

                elif isinstance(element, ListElement) or (
                    isinstance(element, dict)
                    and element.get("element_type")
                    in (PDFElementType.BULLET_LIST, PDFElementType.NUMBERED_LIST)
                ):
                    items = (
                        element.items
                        if isinstance(element, ListElement)
                        else element.get("items", [])
                    )
                    is_numbered = (
                        element.is_numbered
                        if isinstance(element, ListElement)
                        else element.get("is_numbered", False)
                    )

                    for idx, item in enumerate(items, 1):
                        prefix = f"{idx}." if is_numbered else "&bull;"
                        item_text = f"<font color='#2B6CB0'>{prefix}</font> {item}"
                        list_item_style = ParagraphStyle(
                            f"DocListItem_{idx}",
                            parent=body_style,
                            leftIndent=16,
                            firstLineIndent=-12,
                            spaceAfter=3,
                        )
                        flowables.append(Paragraph(item_text, list_item_style))
                    flowables.append(Spacer(1, 4))

                elif isinstance(element, TableElement) or (
                    isinstance(element, dict)
                    and element.get("element_type") == PDFElementType.TABLE
                ):
                    headers = (
                        element.headers
                        if isinstance(element, TableElement)
                        else element.get("headers", [])
                    )
                    rows = (
                        element.rows
                        if isinstance(element, TableElement)
                        else element.get("rows", [])
                    )

                    table_data: List[List[Any]] = []
                    if headers:
                        header_cells = [
                            Paragraph(
                                f"<b>{h}</b>",
                                ParagraphStyle(
                                    "TH", parent=body_style, textColor=colors.white
                                ),
                            )
                            for h in headers
                        ]
                        table_data.append(header_cells)

                    for row in rows:
                        row_cells = [Paragraph(cell, body_style) for cell in row]
                        table_data.append(row_cells)

                    if table_data:
                        t = Table(table_data, colWidths=None)
                        t.setStyle(
                            TableStyle(
                                [
                                    (
                                        "BACKGROUND",
                                        (0, 0),
                                        (-1, 0),
                                        colors.HexColor("#2B6CB0"),
                                    ),
                                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                                    (
                                        "ROWBACKGROUNDS",
                                        (0, 1),
                                        (-1, -1),
                                        [colors.white, colors.HexColor("#F7FAFC")],
                                    ),
                                    (
                                        "GRID",
                                        (0, 0),
                                        (-1, -1),
                                        0.5,
                                        colors.HexColor("#E2E8F0"),
                                    ),
                                ]
                            )
                        )
                        flowables.append(Spacer(1, 4))
                        flowables.append(t)
                        flowables.append(Spacer(1, 8))

                elif isinstance(element, CodeBlockElement) or (
                    isinstance(element, dict)
                    and element.get("element_type") == PDFElementType.CODE_BLOCK
                ):
                    code = (
                        element.code
                        if isinstance(element, CodeBlockElement)
                        else element.get("code", "")
                    )
                    lang = (
                        element.language
                        if isinstance(element, CodeBlockElement)
                        else element.get("language", None)
                    )

                    code_html = (
                        code.replace("&", "&amp;")
                        .replace("<", "&lt;")
                        .replace(">", "&gt;")
                        .replace("\n", "<br/>")
                    )
                    header_str = f"<i>[{lang}]</i><br/>" if lang else ""
                    flowables.append(Paragraph(f"{header_str}{code_html}", code_style))

            # Build PDF Document
            doc = SimpleDocTemplate(
                str(target_path),
                pagesize=letter,
                leftMargin=54,
                rightMargin=54,
                topMargin=54,
                bottomMargin=54,
            )

            doc.build(flowables, canvasmaker=NumberedCanvas)

        except Exception as exc:
            logger.error(
                f"Error during PDF document rendering: {str(exc)}", exc_info=True
            )
            raise ToolExecutionException(
                message=f"Failed to render PDF document: {str(exc)}",
                details={"output_path": str(target_path), "error": str(exc)},
            ) from exc

        # Step 5: Validate Generated PDF File
        self.validate_generated_pdf(target_path)

        # Step 6: Calculate Metrics & Checksum
        file_size = target_path.stat().st_size
        checksum = self._calculate_checksum(target_path)
        page_count = self._extract_page_count(target_path)

        duration = time.time() - start_time
        logger.info(
            f"Successfully generated PDF '{target_path.name}' "
            f"({file_size} bytes, {page_count} pages) in {duration:.3f}s"
        )

        # Return Result
        return PDFGenerationResult(
            filepath=str(target_path),
            file_name=target_path.name,
            size_bytes=file_size,
            page_count=page_count,
            checksum=checksum,
            created_at=datetime.now(timezone.utc),
            status="SUCCESS",
            metadata={
                "title": input_data.title,
                "author": input_data.author,
                "element_count": len(input_data.elements),
                "duration_seconds": round(duration, 4),
            },
        )

    def validate_generated_pdf(self, pdf_path: Path) -> None:
        """
        Validates output file exists, is non-empty, and has valid PDF magic bytes.
        """
        if not pdf_path.exists():
            raise ToolExecutionException(
                message=f"Generated PDF file does not exist at '{pdf_path}'.",
                details={"filepath": str(pdf_path)},
            )

        if pdf_path.stat().st_size == 0:
            raise ToolExecutionException(
                message=f"Generated PDF file at '{pdf_path}' is empty (0 bytes).",
                details={"filepath": str(pdf_path)},
            )

        try:
            with open(pdf_path, "rb") as f:
                header = f.read(5)
                if header != b"%PDF-":
                    raise ToolExecutionException(
                        message=(
                            f"Invalid PDF file header '{header!r}' at '{pdf_path}'."
                        ),
                        details={"filepath": str(pdf_path), "header": str(header)},
                    )
        except ToolExecutionException:
            raise
        except Exception as exc:
            raise ToolExecutionException(
                message=f"Failed to read generated PDF file header: {str(exc)}",
                details={"filepath": str(pdf_path), "error": str(exc)},
            ) from exc

    def create_artifact(
        self,
        result: PDFGenerationResult,
        workflow_id: UUID,
        task_id: Optional[UUID] = None,
    ) -> Artifact:
        """
        Constructs a system Artifact object for the generated PDF file.
        """
        return Artifact(
            workflow_id=workflow_id,
            task_id=task_id,
            name=result.file_name,
            filepath=result.filepath,
            artifact_type=ArtifactType.PDF,
            size_bytes=result.size_bytes,
            checksum=result.checksum,
            created_at=result.created_at,
            metadata=result.metadata,
        )

    @staticmethod
    def _calculate_checksum(path: Path) -> str:
        hasher = hashlib.sha256()
        with open(path, "rb") as f:
            while chunk := f.read(65536):
                hasher.update(chunk)
        return hasher.hexdigest()

    @staticmethod
    def _extract_page_count(path: Path) -> int:
        """Counts pages by scanning PDF page object markers."""
        try:
            with open(path, "rb") as f:
                content = f.read()
                count = (
                    content.count(b"/Type /Page\n")
                    + content.count(b"/Type /Page/")
                    + content.count(b"/Type/Page")
                )
                return max(1, count)
        except Exception:
            return 1
