from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from shared.contracts.artifact import Artifact
from shared.contracts.task import Task


class ExecutionMetrics(BaseModel):
    """Runtime performance and resource metrics for a task execution."""

    execution_time_ms: float = Field(default=0.0, ge=0.0)
    memory_usage_mb: float | None = Field(default=None, ge=0.0)
    cpu_usage_percent: float | None = Field(default=None, ge=0.0)
    exit_code: int | None = None


class TaskError(BaseModel):
    """Structured error payload for task execution failures."""

    error_code: str
    error_message: str
    stack_trace: str | None = None
    is_recoverable: bool = True


class ExecutionResult(BaseModel):
    """Execution result contract returned by Worker Agent after task execution."""

    execution_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    success: bool
    output: dict[str, Any] = Field(default_factory=dict)
    artifacts: list[Artifact] = Field(default_factory=list)
    metrics: ExecutionMetrics = Field(default_factory=ExecutionMetrics)
    logs: list[str] = Field(default_factory=list)
    error: TaskError | None = None
    finished_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SupervisorDecision(str, Enum):
    """Possible outcomes of a supervisor validation."""

    PASSED = "PASSED"
    FAILED = "FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    BLOCKED = "BLOCKED"


class SupervisorValidation(BaseModel):
    """Validation report contract generated by Supervisor Agent."""

    validation_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    is_valid: bool
    decision: SupervisorDecision = SupervisorDecision.NEEDS_REVIEW
    checks: dict[str, bool] = Field(default_factory=dict)
    issues: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class HealingResult(BaseModel):
    """Recovery strategy contract generated by Healing Agent."""

    recovery_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    root_cause: str
    recovery_strategy: str
    replacement_tasks: list[Task] = Field(default_factory=list)
    attempt_number: int = Field(default=1, ge=1)
    success: bool
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class FailureType(str, Enum):
    """Classification of task execution failures."""

    WORKER_FAILURE = "WORKER_FAILURE"
    TOOL_ERROR = "TOOL_ERROR"
    OUTPUT_MISSING = "OUTPUT_MISSING"
    ARTIFACT_VALIDATION_FAILED = "ARTIFACT_VALIDATION_FAILED"
    TIMEOUT = "TIMEOUT"
    DEPENDENCY_FAILED = "DEPENDENCY_FAILED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    TOOL_UNAVAILABLE = "TOOL_UNAVAILABLE"
    UNEXPECTED_EXCEPTION = "UNEXPECTED_EXCEPTION"
    WORKFLOW_BLOCKED = "WORKFLOW_BLOCKED"


class TaskFailureReport(BaseModel):
    """Structured failure report produced by Supervisor Agent."""

    failure_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    failure_type: FailureType
    message: str
    detected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    retryability: bool
    execution_context: dict[str, Any] = Field(default_factory=dict)


class WorkerReexecutionRequest(BaseModel):
    """Controlled re-execution request contract for a task under recovery flow."""

    request_id: UUID = Field(default_factory=uuid4)
    attempt_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    attempt_number: int = Field(default=1, ge=1)
    recovery_plan_id: UUID | None = None
    recovery_strategy: str | None = None
    modified_parameters: dict[str, Any] = Field(default_factory=dict)
    original_task_snapshot: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class WorkerReexecutionResult(BaseModel):
    """Contract representing the outcome of a worker re-execution attempt."""

    reexecution_id: UUID = Field(default_factory=uuid4)
    attempt_id: UUID
    task_id: UUID
    workflow_id: UUID
    attempt_number: int
    execution_result: ExecutionResult
    previous_attempt_ids: list[UUID] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
