from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from shared.contracts.artifact import Artifact
from shared.contracts.task import Task


class ExecutionMetrics(BaseModel):
    """Runtime performance and resource metrics for a task execution."""

    execution_time_ms: float = Field(default=0.0, ge=0.0)
    memory_usage_mb: Optional[float] = Field(default=None, ge=0.0)
    cpu_usage_percent: Optional[float] = Field(default=None, ge=0.0)
    exit_code: Optional[int] = None


class TaskError(BaseModel):
    """Structured error payload for task execution failures."""

    error_code: str
    error_message: str
    stack_trace: Optional[str] = None
    is_recoverable: bool = True


class ExecutionResult(BaseModel):
    """Execution result contract returned by Worker Agent after task execution."""

    execution_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    success: bool
    output: Dict[str, Any] = Field(default_factory=dict)
    artifacts: List[Artifact] = Field(default_factory=list)
    metrics: ExecutionMetrics = Field(default_factory=ExecutionMetrics)
    logs: List[str] = Field(default_factory=list)
    error: Optional[TaskError] = None
    finished_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SupervisorValidation(BaseModel):
    """Validation report contract generated by Supervisor Agent."""

    validation_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    is_valid: bool
    checks: Dict[str, bool] = Field(default_factory=dict)
    issues: List[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class HealingResult(BaseModel):
    """Recovery strategy contract generated by Healing Agent."""

    recovery_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    root_cause: str
    recovery_strategy: str
    replacement_tasks: List[Task] = Field(default_factory=list)
    attempt_number: int = Field(default=1, ge=1)
    success: bool
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
