"""Root Cause Analysis contracts for the Healing Agent."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class RootCauseCategory(str, Enum):
    """Broad classification categories for task failure root causes."""

    INFRASTRUCTURE = "INFRASTRUCTURE"
    TOOL = "TOOL"
    PERMISSION = "PERMISSION"
    NETWORK = "NETWORK"
    RUNTIME = "RUNTIME"
    USER = "USER"
    WORKFLOW = "WORKFLOW"
    EXTERNAL_API = "EXTERNAL_API"
    UNKNOWN = "UNKNOWN"


class DiagnosticEvidence(BaseModel):
    """Structured evidence collected during root cause analysis."""

    observed_failure_type: str | None = None
    observed_error_message: str | None = None
    inspected_logs_count: int = 0
    matched_patterns: list[str] = Field(default_factory=list)
    missing_paths: list[str] = Field(default_factory=list)
    dependency_status: dict[str, Any] = Field(default_factory=dict)
    tool_status: dict[str, Any] = Field(default_factory=dict)
    context_signals: dict[str, Any] = Field(default_factory=dict)


class AlternativeCause(BaseModel):
    """Ranked secondary explanation for a task failure."""

    category: RootCauseCategory
    cause_code: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    explanation: str


class RootCauseResult(BaseModel):
    """Diagnostic outcome model generated by the Root Cause Analyzer."""

    analysis_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    likely_root_cause: str
    category: RootCauseCategory
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    is_confident: bool = True
    diagnostic_explanation: str
    evidence: DiagnosticEvidence = Field(default_factory=DiagnosticEvidence)
    alternative_causes: list[AlternativeCause] = Field(default_factory=list)
    analyzed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def summary(self) -> str:
        return self.likely_root_cause

    @property
    def root_cause_summary(self) -> str:
        return self.likely_root_cause

    @property
    def root_cause_id(self) -> UUID:
        return self.analysis_id

    @property
    def explanation(self) -> str:
        return self.diagnostic_explanation

    @property
    def is_recoverable(self) -> bool:
        return self.category not in (RootCauseCategory.PERMISSION, RootCauseCategory.USER)

    @property
    def recommended_strategy(self) -> str:
        if self.category == RootCauseCategory.PERMISSION:
            return "REQUEST_PERMISSION_AGAIN"
        elif self.category == RootCauseCategory.TOOL:
            return "ALTERNATIVE_TOOL"
        elif self.category == RootCauseCategory.NETWORK:
            return "RETRY"
        elif self.category == RootCauseCategory.USER:
            return "ESCALATE_USER"
        return "RETRY"

    @property
    def context(self) -> dict[str, Any]:
        res = dict(self.evidence.context_signals)
        if self.evidence.observed_failure_type:
            res["observed_failure_type"] = self.evidence.observed_failure_type
        if self.evidence.observed_error_message:
            res["observed_error_message"] = self.evidence.observed_error_message
        return res




__all__ = [
    "AlternativeCause",
    "DiagnosticEvidence",
    "RootCauseCategory",
    "RootCauseResult",
]
