"""Root Cause Analysis contracts for the Healing Agent."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class RootCauseCategory(str, Enum):
    """Broad classification categories for task failure root causes."""

    INFRASTRUCTURE = "INFRASTRUCTURE"
    TOOL = "TOOL"
    PERMISSION = "PERMISSION"
    NETWORK = "NETWORK"
    RUNTIME = "RUNTIME"
    USER = "USER"
    WORKFLOW = "WORKFLOW"
    EXTERNAL_API = "EXTERNAL_API"
    UNKNOWN = "UNKNOWN"


class DiagnosticEvidence(BaseModel):
    """Structured evidence collected during root cause analysis."""

    observed_failure_type: str | None = None
    observed_error_message: str | None = None
    inspected_logs_count: int = 0
    matched_patterns: list[str] = Field(default_factory=list)
    missing_paths: list[str] = Field(default_factory=list)
    dependency_status: dict[str, Any] = Field(default_factory=dict)
    tool_status: dict[str, Any] = Field(default_factory=dict)
    context_signals: dict[str, Any] = Field(default_factory=dict)


class AlternativeCause(BaseModel):
    """Ranked secondary explanation for a task failure."""

    category: RootCauseCategory
    cause_code: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    explanation: str


class RootCauseResult(BaseModel):
    """Diagnostic outcome model generated by the Root Cause Analyzer."""

    analysis_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    likely_root_cause: str
    category: RootCauseCategory
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    is_confident: bool = True
    diagnostic_explanation: str
    evidence: DiagnosticEvidence = Field(default_factory=DiagnosticEvidence)
    alternative_causes: list[AlternativeCause] = Field(default_factory=list)
    analyzed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


__all__ = [
    "AlternativeCause",
    "DiagnosticEvidence",
    "RootCauseCategory",
    "RootCauseResult",
]
