from datetime import datetime, timezone
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from shared.contracts.execution import FailureType
from shared.contracts.permission import PermissionType, RiskLevel


class CompatStrategy:
    def __init__(self, val: str) -> None:
        self.value = val

    def __str__(self) -> str:
        return self.value

    def __eq__(self, other: Any) -> bool:
        if hasattr(other, "value"):
            return self.value == other.value
        return self.value == str(other)


class ErrorParserOutput(BaseModel):
    """Structured payload produced by Error Parser."""

    failure_id: UUID = Field(default_factory=uuid4)
    task_id: UUID
    workflow_id: UUID
    failure_type: FailureType
    raw_error_message: str
    error_code: str = ""
    parsed_details: dict[str, Any] = Field(default_factory=dict)
    is_retryable: bool = True
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class RootCauseAnalysis(BaseModel):
    """Structured root cause diagnosis produced by Root Cause Analyzer."""

    analysis_id: UUID = Field(default_factory=uuid4)
    failure_id: UUID
    task_id: UUID
    workflow_id: UUID
    root_cause_summary: str
    category: str = "UNKNOWN"
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0)
    underlying_factors: list[str] = Field(default_factory=list)
    context: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class RecoveryAction(BaseModel):
    """Structured representation of an individual recovery action within a plan."""

    action_id: UUID = Field(default_factory=uuid4)
    action_type: str = Field(
        ...,
        description=(
            "Action classification tag (e.g., VERIFY_DIR, CREATE_DIR, RETRY_TASK)"
        ),
    )
    description: str = Field(
        ..., description="Detailed description of the recovery step"
    )
    target_tool: str | None = Field(
        default=None, description="Tool targeted by this action, if any"
    )
    required_capabilities: list[str] = Field(
        default_factory=list, description="Capabilities needed for execution"
    )
    required_permissions: list[PermissionType] = Field(
        default_factory=list, description="Permissions required for this action"
    )
    risk_level: RiskLevel = Field(
        default=RiskLevel.LOW,
        description="Assessed risk level for this recovery action",
    )
    preconditions: list[str] = Field(
        default_factory=list,
        description="Conditions that must hold before executing action",
    )
    success_criteria: list[str] = Field(
        default_factory=list, description="Criteria defining successful completion"
    )
    failure_criteria: list[str] = Field(
        default_factory=list, description="Criteria defining action failure"
    )
    action_parameters: dict[str, Any] = Field(
        default_factory=dict, description="Parameters required for action execution"
    )


class RecoveryPlan(BaseModel):
    """Complete, structured recovery plan generated by Recovery Planner."""

    plan_id: UUID = Field(default_factory=uuid4)
    failure_id: UUID
    task_id: UUID
    workflow_id: UUID
    strategy_name: str = Field(..., description="Name of the applied recovery strategy")
    root_cause: str = Field(..., description="Root cause description for reference")
    actions: list[RecoveryAction] = Field(
        default_factory=list, description="Ordered recovery actions"
    )
    overall_risk_level: RiskLevel = Field(
        default=RiskLevel.SAFE, description="Highest risk level among all actions"
    )
    required_permissions: list[PermissionType] = Field(
        default_factory=list, description="Aggregate required permissions"
    )
    required_tools: list[str] = Field(
        default_factory=list, description="Aggregate required tools"
    )
    required_capabilities: list[str] = Field(
        default_factory=list, description="Aggregate required capabilities"
    )
    max_retries: int = Field(
        default=3, description="Maximum retry limit for recovery strategy"
    )
    is_viable: bool = Field(
        default=True, description="Whether a viable recovery plan could be formulated"
    )
    validation_status: str = Field(
        default="PENDING", description="Validation status: PENDING, VALID, or INVALID"
    )
    validation_errors: list[str] = Field(
        default_factory=list, description="Errors identified during plan validation"
    )
    task_context: dict[str, Any] = Field(
        default_factory=dict,
        description="Task context metadata associated with failure",
    )
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def strategy(self) -> CompatStrategy:
        return CompatStrategy(self.strategy_name)

    @property
    def replacement_tasks(self) -> list[Any]:
        if hasattr(self, "_replacement_tasks"):
            return self._replacement_tasks
        return []

    @replacement_tasks.setter
    def replacement_tasks(self, val: list[Any]) -> None:
        self._replacement_tasks = val

    @property
    def is_executable(self) -> bool:
        return self.is_viable

    @property
    def requires_permission(self) -> bool:
        return len(self.required_permissions) > 0
