import React, { useState } from 'react';

interface ArtifactItem {
  title: string;
  icon: string;
  type: string;
  date: string;
  color: string;
  description: string;
  size?: string;
}

export const ArtifactsPage: React.FC = () => {
  const [artifacts] = useState<ArtifactItem[]>([
    {
      title: 'Downloads Map.json',
      icon: 'description',
      type: 'JSON',
      date: 'Just Now',
      color: 'text-primary',
      description: 'Final output generated from Download Migration workflow.',
      size: '14 KB',
    },
    {
      title: 'Organize_Report.pdf',
      icon: 'picture_as_pdf',
      type: 'PDF',
      date: '2 mins ago',
      color: 'text-error',
      description: 'Summary PDF document with category breakdowns.',
      size: '240 KB',
    },
    {
      title: 'Migration_Log.csv',
      icon: 'table_chart',
      type: 'CSV',
      date: 'Today, 10:42 AM',
      color: 'text-accent-electric',
      description: 'Tabular log of all 142 migrated file paths and timestamps.',
      size: '38 KB',
    },
    {
      title: 'Q3_AI_Strategy.pptx',
      icon: 'co_present',
      type: 'PPTX',
      date: 'Yesterday',
      color: 'text-primary',
      description: 'Comprehensive presentation deck with executive summary.',
      size: '1.8 MB',
    },
  ]);

  const [previewItem, setPreviewItem] = useState<ArtifactItem | null>(null);

  const handleDownload = (item: ArtifactItem) => {
    const blob = new Blob([`Dummy preview for ${item.title}`], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = item.title;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col flex-1 min-h-[calc(100vh-4rem)]">
      <main className="p-6 md:p-10 max-w-6xl mx-auto w-full flex flex-col gap-10 flex-1">
        <section className="text-center py-12 border-b border-outline-variant/20 rounded-3xl bg-surface-container/30 px-4">
          <h2 className="text-xs font-bold text-primary uppercase tracking-[0.3em] mb-4">
            Open Source • Local Runtime
          </h2>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-4 text-white">
            Generated <span className="italic text-primary font-serif">Artifacts</span>
          </h1>
          <p className="text-base md:text-lg text-on-surface-muted max-w-2xl mx-auto">
            Access and manage the outputs generated by your agents during task execution.
          </p>
        </section>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {artifacts.map((art, i) => (
            <div
              key={i}
              onClick={() => setPreviewItem(art)}
              className="group glass-panel rounded-2xl overflow-hidden flex flex-col hover:border-primary transition-all cursor-pointer shadow-sm hover:shadow-[0_8px_30px_rgba(168,85,247,0.2)]"
            >
              <div className="h-36 bg-surface-container-high flex items-center justify-center border-b border-outline-variant/40 relative">
                <span
                  className={`material-symbols-outlined text-5xl opacity-40 group-hover:scale-110 transition-transform ${art.color}`}
                >
                  {art.icon}
                </span>
                <div className="absolute top-3 right-3 bg-surface-deep/90 rounded-md px-2 py-0.5 text-[10px] font-bold border border-outline-variant/50 shadow-sm text-white">
                  {art.type}
                </div>
              </div>
              <div className="p-5 flex flex-col flex-1">
                <h3 className="font-bold text-base md:text-lg mb-1 truncate text-white">{art.title}</h3>
                <p className="text-xs text-on-surface-muted mb-4 line-clamp-2 leading-relaxed">
                  {art.description}
                </p>
                <div className="mt-auto flex justify-between items-center text-[10px] font-bold text-on-surface-muted uppercase">
                  <span>{art.date}</span>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDownload(art);
                    }}
                    className="p-1.5 rounded-lg hover:bg-surface-variant hover:text-primary transition-colors cursor-pointer"
                    title="Download"
                  >
                    <span className="material-symbols-outlined text-base">download</span>
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </main>

      {/* Preview Modal */}
      {previewItem && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
          <div className="glass-panel w-full max-w-lg rounded-2xl overflow-hidden glow-active">
            <div className="p-5 border-b border-outline-variant/40 flex justify-between items-center">
              <div className="flex items-center gap-3">
                <span className="material-symbols-outlined text-primary text-2xl">{previewItem.icon}</span>
                <h3 className="font-bold text-white text-lg">{previewItem.title}</h3>
              </div>
              <button
                onClick={() => setPreviewItem(null)}
                className="text-on-surface-muted hover:text-white"
              >
                <span className="material-symbols-outlined">close</span>
              </button>
            </div>
            <div className="p-6 flex flex-col gap-4">
              <div className="bg-surface-deep p-4 rounded-xl border border-outline-variant/40 font-mono text-xs text-on-surface-variant">
                <p className="mb-2 text-primary font-bold">{`// Artifact Metadata`}</p>
                <p>Type: {previewItem.type}</p>
                <p>Created: {previewItem.date}</p>
                <p>Size: {previewItem.size || '32 KB'}</p>
                <p className="mt-2 text-white">Status: Verified by Supervisor Agent</p>
              </div>
              <p className="text-sm text-on-surface-muted">{previewItem.description}</p>
            </div>
            <div className="p-5 border-t border-outline-variant/40 flex justify-end gap-3 bg-surface-container-low/40">
              <button
                onClick={() => setPreviewItem(null)}
                className="px-5 py-2 rounded-lg border border-outline-variant text-sm text-on-surface-muted hover:bg-surface-variant"
              >
                Close
              </button>
              <button
                onClick={() => {
                  handleDownload(previewItem);
                  setPreviewItem(null);
                }}
                className="px-6 py-2 rounded-lg bg-primary text-white text-sm font-bold hover:bg-accent-electric flex items-center gap-2"
              >
                <span className="material-symbols-outlined text-sm">download</span>
                Download
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
