import React, { useState } from 'react';

interface ArtifactItem {
  title: string;
  icon: string;
  type: string;
  date: string;
  color: string;
  description: string;
  size?: string;
}

export const ArtifactsPage: React.FC = () => {
  const [artifacts] = useState<ArtifactItem[]>([
    {
      title: 'Downloads Map.json',
      icon: 'description',
      type: 'JSON',
      date: 'Just Now',
      color: 'text-primary',
      description: 'Final output generated from Download Migration workflow.',
      size: '14 KB',
    },
    {
      title: 'Organize_Report.pdf',
      icon: 'picture_as_pdf',
      type: 'PDF',
      date: '2 mins ago',
      color: 'text-error',
      description: 'Summary PDF document with category breakdowns.',
      size: '240 KB',
    },
    {
      title: 'Migration_Log.csv',
      icon: 'table_chart',
      type: 'CSV',
      date: 'Today, 10:42 AM',
      color: 'text-accent-electric',
      description: 'Tabular log of all 142 migrated file paths and timestamps.',
      size: '38 KB',
    },
    {
      title: 'Q3_AI_Strategy.pptx',
      icon: 'co_present',
      type: 'PPTX',
      date: 'Yesterday',
      color: 'text-primary',
      description: 'Comprehensive presentation deck with executive summary.',
      size: '1.8 MB',
    },
  ]);

  const [previewItem, setPreviewItem] = useState<ArtifactItem | null>(null);

  const handleDownload = (item: ArtifactItem) => {
    const blob = new Blob([`Dummy preview for ${item.title}`], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = item.title;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col flex-1 min-h-[calc(100vh-4rem)]">
      <main className="p-6 md:p-10 max-w-6xl mx-auto w-full flex flex-col gap-10 flex-1">
        <section className="text-center py-12 rounded-3xl glass-card px-4 border border-white/15">
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-4 text-white drop-shadow">
            Generated <span className="italic bg-gradient-to-r from-cyan-300 to-indigo-300 bg-clip-text text-transparent font-serif">Artifacts</span>
          </h1>
          <p className="text-base md:text-lg text-slate-300 max-w-2xl mx-auto drop-shadow">
            Access and manage the outputs generated by your agents during task execution.
          </p>
        </section>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {artifacts.map((art, i) => (
            <div
              key={i}
              onClick={() => setPreviewItem(art)}
              className="group glass-card rounded-2xl overflow-hidden flex flex-col hover:border-cyan-400/60 transition-all cursor-pointer shadow-lg hover:shadow-cyan-500/20"
            >
              <div className="h-36 bg-black/30 flex items-center justify-center border-b border-white/10 relative">
                <span
                  className={`material-symbols-outlined text-5xl opacity-60 group-hover:scale-110 transition-transform ${
                    art.type === 'PDF' ? 'text-rose-400' : art.type === 'JSON' ? 'text-cyan-400' : art.type === 'PPTX' ? 'text-amber-400' : 'text-emerald-400'
                  }`}
                >
                  {art.icon}
                </span>
                <div className="absolute top-3 right-3 bg-black/50 backdrop-blur-md rounded-lg px-2.5 py-0.5 text-[10px] font-bold border border-white/20 shadow-sm text-white font-mono">
                  {art.type}
                </div>
              </div>
              <div className="p-5 flex flex-col flex-1">
                <h3 className="font-bold text-base md:text-lg mb-1 truncate text-white drop-shadow">{art.title}</h3>
                <p className="text-xs text-slate-300 mb-4 line-clamp-2 leading-relaxed font-medium">
                  {art.description}
                </p>
                <div className="mt-auto flex justify-between items-center text-[10px] font-bold text-slate-400 uppercase font-mono">
                  <span>{art.date}</span>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDownload(art);
                    }}
                    className="p-1.5 rounded-lg hover:bg-white/10 hover:text-cyan-300 text-slate-300 transition-colors cursor-pointer"
                    title="Download"
                  >
                    <span className="material-symbols-outlined text-base">download</span>
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </main>

      {/* Preview Modal */}
      {previewItem && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
          <div className="glass-card w-full max-w-lg rounded-2xl overflow-hidden shadow-2xl">
            <div className="p-5 border-b border-white/10 flex justify-between items-center">
              <div className="flex items-center gap-3">
                <span className="material-symbols-outlined text-cyan-300 text-2xl">{previewItem.icon}</span>
                <h3 className="font-bold text-white text-lg drop-shadow">{previewItem.title}</h3>
              </div>
              <button
                onClick={() => setPreviewItem(null)}
                className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-white/10 cursor-pointer"
              >
                <span className="material-symbols-outlined">close</span>
              </button>
            </div>
            <div className="p-6 flex flex-col gap-4">
              <div className="bg-black/40 p-4 rounded-xl border border-white/10 font-mono text-xs text-slate-200 backdrop-blur-md">
                <p className="mb-2 text-cyan-300 font-bold">{`// Artifact Metadata`}</p>
                <p>Type: {previewItem.type}</p>
                <p>Created: {previewItem.date}</p>
                <p>Size: {previewItem.size || '32 KB'}</p>
                <p className="mt-2 text-emerald-400 font-semibold">Status: Verified by Supervisor Agent</p>
              </div>
              <p className="text-sm text-slate-300">{previewItem.description}</p>
            </div>
            <div className="p-5 border-t border-white/10 flex justify-end gap-3 bg-black/20">
              <button
                onClick={() => setPreviewItem(null)}
                className="px-5 py-2 rounded-xl border border-white/20 text-sm text-slate-300 hover:bg-white/10 cursor-pointer"
              >
                Close
              </button>
              <button
                onClick={() => {
                  handleDownload(previewItem);
                  setPreviewItem(null);
                }}
                className="px-6 py-2 rounded-xl bg-[#2f70d9] text-white text-sm font-bold hover:bg-blue-600 shadow-lg shadow-blue-500/25 flex items-center gap-2 cursor-pointer active:scale-95"
              >
                <span className="material-symbols-outlined text-sm">download</span>
                Download
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
