import uuid
from typing import Dict, List

from shared.contracts import Task, TaskPriority


class PriorityAssignmentEngine:
    """
    Engine responsible for determining execution priority and ordering
    for a given list of tasks generated by the Task Decomposition Engine.
    """

    _PRIORITY_WEIGHTS = {
        TaskPriority.CRITICAL: 1000,
        TaskPriority.HIGH: 100,
        TaskPriority.MEDIUM: 10,
        TaskPriority.LOW: 1,
    }

    _RISK_WEIGHTS = {
        "CRITICAL": 50,
        "HIGH": 30,
        "MEDIUM": 10,
        "LOW": 0,
        "SAFE": 0,
    }

    def assign_priorities(self, tasks: List[Task]) -> List[Task]:
        """
        Main entry point for priority assignment.
        Upgrades priorities based on dependencies, calculates scores,
        and returns a topologically sorted list of tasks.
        """
        if not tasks:
            return []

        task_map = {task.task_id: task for task in tasks}

        # 1. Propagate priority upwards so tasks blocking
        # high-priority tasks get upgraded
        self._upgrade_priorities(task_map)

        # 2. Perform topological sort and final ordering
        return self._order_tasks(list(task_map.values()))

    def _upgrade_priorities(self, task_map: Dict[uuid.UUID, Task]) -> None:
        """
        Upgrades the priority of tasks if they block tasks with a higher priority.
        """
        # Build reverse dependency graph (child -> parents)
        # dependents[task_id] contains all tasks that depend on task_id
        dependents: Dict[uuid.UUID, List[uuid.UUID]] = {
            tid: [] for tid in task_map.keys()
        }
        for task in task_map.values():
            for dep_id in task.dependencies:
                if dep_id in dependents:
                    dependents[dep_id].append(task.task_id)

        # Iteratively upgrade priorities
        changed = True
        while changed:
            changed = False
            for task_id, task in task_map.items():
                current_weight = self._PRIORITY_WEIGHTS[task.priority]
                for dependent_id in dependents[task_id]:
                    dependent_task = task_map[dependent_id]
                    dependent_weight = self._PRIORITY_WEIGHTS[dependent_task.priority]

                    if dependent_weight > current_weight:
                        # Upgrade to match dependent
                        task.priority = dependent_task.priority
                        current_weight = dependent_weight
                        changed = True

    def _calculate_score(self, task: Task) -> int:
        """
        Calculate a numeric score for a task to resolve ties during topological sort.
        Higher score means it should be executed earlier if possible.
        """
        score = self._PRIORITY_WEIGHTS.get(task.priority, 0)
        score += self._RISK_WEIGHTS.get(task.risk_level.upper(), 0)
        return score

    def _order_tasks(self, tasks: List[Task]) -> List[Task]:
        """
        Performs a topological sort respecting dependencies.
        When multiple tasks are available (in-degree 0), selects the one
        with the highest priority score.
        """
        task_map = {task.task_id: task for task in tasks}

        # Build graph
        # in_degree[task_id] = number of uncompleted dependencies
        in_degree: Dict[uuid.UUID, int] = {tid: 0 for tid in task_map.keys()}
        # dependents[task_id] = list of tasks that depend on this task
        dependents: Dict[uuid.UUID, List[uuid.UUID]] = {
            tid: [] for tid in task_map.keys()
        }

        for task in tasks:
            for dep_id in task.dependencies:
                # Only consider dependencies that are in the current batch
                if dep_id in task_map:
                    in_degree[task.task_id] += 1
                    dependents[dep_id].append(task.task_id)

        # Find all tasks with no dependencies
        available_tasks = [
            task_id for task_id, degree in in_degree.items() if degree == 0
        ]

        ordered_tasks = []

        while available_tasks:
            # To make it deterministic: highest score first,
            # if tied, lowest UUID string first.
            available_tasks.sort(
                key=lambda tid: (-self._calculate_score(task_map[tid]), str(tid))
            )

            # Pop the first element (highest priority)
            current_id = available_tasks.pop(0)
            ordered_tasks.append(task_map[current_id])

            # Decrease in-degree of dependents
            for dependent_id in dependents[current_id]:
                in_degree[dependent_id] -= 1
                if in_degree[dependent_id] == 0:
                    available_tasks.append(dependent_id)

        # Check for cycles
        if len(ordered_tasks) != len(tasks):
            raise ValueError("Dependency cycle detected among tasks.")

        return ordered_tasks
