import tempfile
from pathlib import Path
from uuid import uuid4

import pytest
from shared.contracts.artifact import ArtifactType
from shared.contracts.permission import PermissionType, RiskLevel
from shared.contracts.task import Task, TaskCategory

from app.agents.worker.pdf_worker import PDFWorkerAgent
from app.core.permissions import PermissionManager
from app.tools.pdf.tool import register_pdf_tool
from app.tools.registry import ToolRegistry


class TestPDFWorkerAgent:
    """Test suite for PDFWorkerAgent execution."""

    @pytest.fixture
    def temp_dir(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            yield Path(tmpdir)

    @pytest.mark.asyncio
    async def test_pdf_worker_successful_task_execution(self, temp_dir):
        registry = ToolRegistry()
        register_pdf_tool(registry)
        permission_manager = PermissionManager(auto_approve_low_risk=False)

        worker = PDFWorkerAgent(
            tool_registry=registry, permission_manager=permission_manager
        )
        workflow_id = uuid4()
        output_file = temp_dir / "worker_report.pdf"

        # Grant Permission
        req = await permission_manager.request_permission(
            workflow_id=workflow_id,
            permission_type=PermissionType.FILE_SYSTEM,
            reason="PDF Generation",
            risk_level=RiskLevel.MEDIUM,
        )
        await permission_manager.grant_permission(req.permission_id)

        task = Task(
            workflow_id=workflow_id,
            task_name="Generate Summary PDF",
            description="Convert summary content to PDF document",
            required_tool="pdf_generator",
            category=TaskCategory.PDF_GENERATION,
            expected_output="Valid PDF file",
        )

        payload = {
            "title": "Worker Executive Report",
            "subtitle": "Generated by Worker Agent",
            "author": "AI Worker",
            "elements": [
                {"element_type": "heading", "text": "Section 1", "level": 1},
                {"element_type": "paragraph", "text": "Task completed successfully."},
            ],
            "output_path": str(output_file),
        }

        result = worker.execute_task(task, payload=payload, workflow_id=workflow_id)

        assert result.success is True
        assert result.task_id == task.task_id
        assert result.workflow_id == workflow_id
        assert len(result.artifacts) == 1
        assert result.artifacts[0].artifact_type == ArtifactType.PDF
        assert result.artifacts[0].filepath == str(output_file.resolve())
        assert result.metrics.execution_time_ms > 0
        assert output_file.exists()

    def test_pdf_worker_missing_tool_error(self, temp_dir):
        empty_registry = ToolRegistry()
        worker = PDFWorkerAgent(tool_registry=empty_registry)
        workflow_id = uuid4()
        output_file = temp_dir / "missing_tool.pdf"

        task = Task(
            workflow_id=workflow_id,
            task_name="Generate PDF",
            description="Generate PDF document",
            required_tool="unregistered_tool",
            category=TaskCategory.PDF_GENERATION,
            expected_output="Valid PDF file",
        )

        payload = {
            "title": "Missing Tool Test",
            "output_path": str(output_file),
        }

        result = worker.execute_task(task, payload=payload, workflow_id=workflow_id)

        assert result.success is False
        assert result.error is not None
        assert result.error.error_code == "TOOL_NOT_FOUND"

    @pytest.mark.asyncio
    async def test_pdf_worker_permission_denial(self, temp_dir):
        registry = ToolRegistry()
        register_pdf_tool(registry)
        permission_manager = PermissionManager(auto_approve_low_risk=False)

        worker = PDFWorkerAgent(
            tool_registry=registry, permission_manager=permission_manager
        )
        workflow_id = uuid4()
        output_file = temp_dir / "denied.pdf"

        # Request permission without granting
        await permission_manager.request_permission(
            workflow_id=workflow_id,
            permission_type=PermissionType.FILE_SYSTEM,
            reason="PDF Generation",
            risk_level=RiskLevel.HIGH,
        )

        task = Task(
            workflow_id=workflow_id,
            task_name="Generate PDF",
            description="Generate PDF document",
            required_tool="pdf_generator",
            category=TaskCategory.PDF_GENERATION,
            expected_output="Valid PDF file",
        )

        payload = {
            "title": "Denied Test",
            "output_path": str(output_file),
        }

        result = worker.execute_task(task, payload=payload, workflow_id=workflow_id)

        assert result.success is False
        assert result.error is not None
        assert result.error.error_code == "PERMISSION_DENIED"
        assert not output_file.exists()
