import tempfile
from pathlib import Path
from uuid import uuid4

import pytest
from shared.contracts.artifact import ArtifactType
from shared.contracts.task import Task, TaskCategory

from app.agents.worker.document_worker import DocumentWorkerAgent
from app.core.permissions import PermissionManager, PermissionType
from app.tools.document.tool import register_document_tool
from app.tools.registry import ToolRegistry


class TestDocumentWorkerAgent:
    """Test suite for DocumentWorkerAgent execution."""

    @pytest.fixture
    def temp_dir(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            yield Path(tmpdir)

    def test_document_worker_successful_task_execution(self, temp_dir):
        registry = ToolRegistry()
        register_document_tool(registry)
        permission_manager = PermissionManager()

        worker = DocumentWorkerAgent(
            tool_registry=registry, permission_manager=permission_manager
        )
        workflow_id = uuid4()
        output_file = temp_dir / "worker_doc.md"

        # Approve permission
        req = permission_manager.request_permission(
            workflow_id=str(workflow_id),
            task_id="task_1",
            permission_type=PermissionType.FILE_WRITE,
            reason="Document Generation",
        )
        permission_manager.approve_permission(req.request_id)

        task = Task(
            workflow_id=workflow_id,
            task_name="Generate Summary Document",
            description="Convert project summary to markdown document",
            required_tool="document_generator",
            category=TaskCategory.CODE_GENERATION,
            expected_output="Valid Markdown document file",
        )

        payload = {
            "title": "Worker Executive Report",
            "subtitle": "Generated by DocumentWorkerAgent",
            "author": "AI Worker",
            "content": "Task executed successfully.",
            "elements": [
                {"element_type": "heading", "text": "Section 1", "level": 1},
                {"element_type": "paragraph", "text": "Details here."},
            ],
            "output_path": str(output_file),
        }

        result = worker.execute_task(task, payload=payload, workflow_id=workflow_id)

        assert result.success is True
        assert result.task_id == task.task_id
        assert result.workflow_id == workflow_id
        assert len(result.artifacts) == 1
        assert result.artifacts[0].artifact_type == ArtifactType.REPORTS
        assert result.artifacts[0].filepath == str(output_file.resolve())
        assert result.metrics.execution_time_ms > 0
        assert output_file.exists()

    def test_document_worker_missing_tool_error(self, temp_dir):
        empty_registry = ToolRegistry()
        worker = DocumentWorkerAgent(tool_registry=empty_registry)
        workflow_id = uuid4()
        output_file = temp_dir / "missing_tool.md"

        task = Task(
            workflow_id=workflow_id,
            task_name="Generate Document",
            description="Generate document",
            required_tool="unregistered_tool",
            category=TaskCategory.CODE_GENERATION,
            expected_output="Valid document file",
        )

        payload = {
            "title": "Missing Tool Test",
            "content": "Missing tool content",
            "output_path": str(output_file),
        }

        result = worker.execute_task(task, payload=payload, workflow_id=workflow_id)

        assert result.success is False
        assert result.error is not None
        assert result.error.error_code == "TOOL_NOT_FOUND"

    def test_document_worker_permission_denial(self, temp_dir):
        registry = ToolRegistry()
        register_document_tool(registry)
        permission_manager = PermissionManager()

        worker = DocumentWorkerAgent(
            tool_registry=registry, permission_manager=permission_manager
        )
        workflow_id = uuid4()
        output_file = temp_dir / "denied.md"

        # Request permission without approving it
        permission_manager.request_permission(
            workflow_id=str(workflow_id),
            task_id="task_1",
            permission_type=PermissionType.FILE_WRITE,
            reason="Document Generation",
        )

        task = Task(
            workflow_id=workflow_id,
            task_name="Generate Document",
            description="Generate document",
            required_tool="document_generator",
            category=TaskCategory.CODE_GENERATION,
            expected_output="Valid document file",
        )

        payload = {
            "title": "Denied Test",
            "content": "Denied content",
            "output_path": str(output_file),
        }

        result = worker.execute_task(task, payload=payload, workflow_id=workflow_id)

        assert result.success is False
        assert result.error is not None
        assert result.error.error_code == "PERMISSION_DENIED"
        assert not output_file.exists()
